/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WindowMainSidebarRouteRouteImport } from './routes/window.main._sidebar/route'
import { Route as WindowMainSplashIndexRouteImport } from './routes/window.main.splash/index'
import { Route as WindowMainSidebarTodayIndexRouteImport } from './routes/window.main._sidebar.today/index'
import { Route as WindowMainSidebarSettingsIndexRouteImport } from './routes/window.main._sidebar.settings/index'
import { Route as WindowMainSidebarSettingsShortcutsIndexRouteImport } from './routes/window.main._sidebar.settings.shortcuts/index'
import { Route as WindowMainSidebarSettingsGeneralIndexRouteImport } from './routes/window.main._sidebar.settings.general/index'
import { Route as WindowMainSidebarSettingsDeveloperIndexRouteImport } from './routes/window.main._sidebar.settings.developer/index'
import { Route as WindowMainSidebarIntentionsNewIndexRouteImport } from './routes/window.main._sidebar.intentions.new/index'

const WindowMainSidebarRouteRoute = WindowMainSidebarRouteRouteImport.update({
  id: '/window/main/_sidebar',
  path: '/window/main',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowMainSplashIndexRoute = WindowMainSplashIndexRouteImport.update({
  id: '/window/main/splash/',
  path: '/window/main/splash/',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowMainSidebarTodayIndexRoute =
  WindowMainSidebarTodayIndexRouteImport.update({
    id: '/today/',
    path: '/today/',
    getParentRoute: () => WindowMainSidebarRouteRoute,
  } as any)
const WindowMainSidebarSettingsIndexRoute =
  WindowMainSidebarSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => WindowMainSidebarRouteRoute,
  } as any)
const WindowMainSidebarSettingsShortcutsIndexRoute =
  WindowMainSidebarSettingsShortcutsIndexRouteImport.update({
    id: '/settings/shortcuts/',
    path: '/settings/shortcuts/',
    getParentRoute: () => WindowMainSidebarRouteRoute,
  } as any)
const WindowMainSidebarSettingsGeneralIndexRoute =
  WindowMainSidebarSettingsGeneralIndexRouteImport.update({
    id: '/settings/general/',
    path: '/settings/general/',
    getParentRoute: () => WindowMainSidebarRouteRoute,
  } as any)
const WindowMainSidebarSettingsDeveloperIndexRoute =
  WindowMainSidebarSettingsDeveloperIndexRouteImport.update({
    id: '/settings/developer/',
    path: '/settings/developer/',
    getParentRoute: () => WindowMainSidebarRouteRoute,
  } as any)
const WindowMainSidebarIntentionsNewIndexRoute =
  WindowMainSidebarIntentionsNewIndexRouteImport.update({
    id: '/intentions/new/',
    path: '/intentions/new/',
    getParentRoute: () => WindowMainSidebarRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/window/main': typeof WindowMainSidebarRouteRouteWithChildren
  '/window/main/splash/': typeof WindowMainSplashIndexRoute
  '/window/main/settings/': typeof WindowMainSidebarSettingsIndexRoute
  '/window/main/today/': typeof WindowMainSidebarTodayIndexRoute
  '/window/main/intentions/new/': typeof WindowMainSidebarIntentionsNewIndexRoute
  '/window/main/settings/developer/': typeof WindowMainSidebarSettingsDeveloperIndexRoute
  '/window/main/settings/general/': typeof WindowMainSidebarSettingsGeneralIndexRoute
  '/window/main/settings/shortcuts/': typeof WindowMainSidebarSettingsShortcutsIndexRoute
}
export interface FileRoutesByTo {
  '/window/main': typeof WindowMainSidebarRouteRouteWithChildren
  '/window/main/splash': typeof WindowMainSplashIndexRoute
  '/window/main/settings': typeof WindowMainSidebarSettingsIndexRoute
  '/window/main/today': typeof WindowMainSidebarTodayIndexRoute
  '/window/main/intentions/new': typeof WindowMainSidebarIntentionsNewIndexRoute
  '/window/main/settings/developer': typeof WindowMainSidebarSettingsDeveloperIndexRoute
  '/window/main/settings/general': typeof WindowMainSidebarSettingsGeneralIndexRoute
  '/window/main/settings/shortcuts': typeof WindowMainSidebarSettingsShortcutsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/window/main/_sidebar': typeof WindowMainSidebarRouteRouteWithChildren
  '/window/main/splash/': typeof WindowMainSplashIndexRoute
  '/window/main/_sidebar/settings/': typeof WindowMainSidebarSettingsIndexRoute
  '/window/main/_sidebar/today/': typeof WindowMainSidebarTodayIndexRoute
  '/window/main/_sidebar/intentions/new/': typeof WindowMainSidebarIntentionsNewIndexRoute
  '/window/main/_sidebar/settings/developer/': typeof WindowMainSidebarSettingsDeveloperIndexRoute
  '/window/main/_sidebar/settings/general/': typeof WindowMainSidebarSettingsGeneralIndexRoute
  '/window/main/_sidebar/settings/shortcuts/': typeof WindowMainSidebarSettingsShortcutsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/window/main'
    | '/window/main/splash/'
    | '/window/main/settings/'
    | '/window/main/today/'
    | '/window/main/intentions/new/'
    | '/window/main/settings/developer/'
    | '/window/main/settings/general/'
    | '/window/main/settings/shortcuts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/window/main'
    | '/window/main/splash'
    | '/window/main/settings'
    | '/window/main/today'
    | '/window/main/intentions/new'
    | '/window/main/settings/developer'
    | '/window/main/settings/general'
    | '/window/main/settings/shortcuts'
  id:
    | '__root__'
    | '/window/main/_sidebar'
    | '/window/main/splash/'
    | '/window/main/_sidebar/settings/'
    | '/window/main/_sidebar/today/'
    | '/window/main/_sidebar/intentions/new/'
    | '/window/main/_sidebar/settings/developer/'
    | '/window/main/_sidebar/settings/general/'
    | '/window/main/_sidebar/settings/shortcuts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WindowMainSidebarRouteRoute: typeof WindowMainSidebarRouteRouteWithChildren
  WindowMainSplashIndexRoute: typeof WindowMainSplashIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/window/main/_sidebar': {
      id: '/window/main/_sidebar'
      path: '/window/main'
      fullPath: '/window/main'
      preLoaderRoute: typeof WindowMainSidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window/main/splash/': {
      id: '/window/main/splash/'
      path: '/window/main/splash'
      fullPath: '/window/main/splash/'
      preLoaderRoute: typeof WindowMainSplashIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window/main/_sidebar/today/': {
      id: '/window/main/_sidebar/today/'
      path: '/today'
      fullPath: '/window/main/today/'
      preLoaderRoute: typeof WindowMainSidebarTodayIndexRouteImport
      parentRoute: typeof WindowMainSidebarRouteRoute
    }
    '/window/main/_sidebar/settings/': {
      id: '/window/main/_sidebar/settings/'
      path: '/settings'
      fullPath: '/window/main/settings/'
      preLoaderRoute: typeof WindowMainSidebarSettingsIndexRouteImport
      parentRoute: typeof WindowMainSidebarRouteRoute
    }
    '/window/main/_sidebar/settings/shortcuts/': {
      id: '/window/main/_sidebar/settings/shortcuts/'
      path: '/settings/shortcuts'
      fullPath: '/window/main/settings/shortcuts/'
      preLoaderRoute: typeof WindowMainSidebarSettingsShortcutsIndexRouteImport
      parentRoute: typeof WindowMainSidebarRouteRoute
    }
    '/window/main/_sidebar/settings/general/': {
      id: '/window/main/_sidebar/settings/general/'
      path: '/settings/general'
      fullPath: '/window/main/settings/general/'
      preLoaderRoute: typeof WindowMainSidebarSettingsGeneralIndexRouteImport
      parentRoute: typeof WindowMainSidebarRouteRoute
    }
    '/window/main/_sidebar/settings/developer/': {
      id: '/window/main/_sidebar/settings/developer/'
      path: '/settings/developer'
      fullPath: '/window/main/settings/developer/'
      preLoaderRoute: typeof WindowMainSidebarSettingsDeveloperIndexRouteImport
      parentRoute: typeof WindowMainSidebarRouteRoute
    }
    '/window/main/_sidebar/intentions/new/': {
      id: '/window/main/_sidebar/intentions/new/'
      path: '/intentions/new'
      fullPath: '/window/main/intentions/new/'
      preLoaderRoute: typeof WindowMainSidebarIntentionsNewIndexRouteImport
      parentRoute: typeof WindowMainSidebarRouteRoute
    }
  }
}

interface WindowMainSidebarRouteRouteChildren {
  WindowMainSidebarSettingsIndexRoute: typeof WindowMainSidebarSettingsIndexRoute
  WindowMainSidebarTodayIndexRoute: typeof WindowMainSidebarTodayIndexRoute
  WindowMainSidebarIntentionsNewIndexRoute: typeof WindowMainSidebarIntentionsNewIndexRoute
  WindowMainSidebarSettingsDeveloperIndexRoute: typeof WindowMainSidebarSettingsDeveloperIndexRoute
  WindowMainSidebarSettingsGeneralIndexRoute: typeof WindowMainSidebarSettingsGeneralIndexRoute
  WindowMainSidebarSettingsShortcutsIndexRoute: typeof WindowMainSidebarSettingsShortcutsIndexRoute
}

const WindowMainSidebarRouteRouteChildren: WindowMainSidebarRouteRouteChildren =
  {
    WindowMainSidebarSettingsIndexRoute: WindowMainSidebarSettingsIndexRoute,
    WindowMainSidebarTodayIndexRoute: WindowMainSidebarTodayIndexRoute,
    WindowMainSidebarIntentionsNewIndexRoute:
      WindowMainSidebarIntentionsNewIndexRoute,
    WindowMainSidebarSettingsDeveloperIndexRoute:
      WindowMainSidebarSettingsDeveloperIndexRoute,
    WindowMainSidebarSettingsGeneralIndexRoute:
      WindowMainSidebarSettingsGeneralIndexRoute,
    WindowMainSidebarSettingsShortcutsIndexRoute:
      WindowMainSidebarSettingsShortcutsIndexRoute,
  }

const WindowMainSidebarRouteRouteWithChildren =
  WindowMainSidebarRouteRoute._addFileChildren(
    WindowMainSidebarRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  WindowMainSidebarRouteRoute: WindowMainSidebarRouteRouteWithChildren,
  WindowMainSplashIndexRoute: WindowMainSplashIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
