/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WindowMainSidebarRouteRouteImport } from './routes/window.main._sidebar/route'
import { Route as WindowMainSplashIndexRouteImport } from './routes/window.main.splash/index'
import { Route as WindowMainSidebarSettingsIndexRouteImport } from './routes/window.main._sidebar.settings/index'
import { Route as WindowMainSidebarHomeIndexRouteImport } from './routes/window.main._sidebar.home/index'
import { Route as WindowMainSidebarSettingsGeneralIndexRouteImport } from './routes/window.main._sidebar.settings.general/index'
import { Route as WindowMainSidebarIntentionsNewIndexRouteImport } from './routes/window.main._sidebar.intentions.new/index'

const WindowMainSidebarRouteRoute = WindowMainSidebarRouteRouteImport.update({
  id: '/window/main/_sidebar',
  path: '/window/main',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowMainSplashIndexRoute = WindowMainSplashIndexRouteImport.update({
  id: '/window/main/splash/',
  path: '/window/main/splash/',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowMainSidebarSettingsIndexRoute =
  WindowMainSidebarSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => WindowMainSidebarRouteRoute,
  } as any)
const WindowMainSidebarHomeIndexRoute =
  WindowMainSidebarHomeIndexRouteImport.update({
    id: '/home/',
    path: '/home/',
    getParentRoute: () => WindowMainSidebarRouteRoute,
  } as any)
const WindowMainSidebarSettingsGeneralIndexRoute =
  WindowMainSidebarSettingsGeneralIndexRouteImport.update({
    id: '/settings/general/',
    path: '/settings/general/',
    getParentRoute: () => WindowMainSidebarRouteRoute,
  } as any)
const WindowMainSidebarIntentionsNewIndexRoute =
  WindowMainSidebarIntentionsNewIndexRouteImport.update({
    id: '/intentions/new/',
    path: '/intentions/new/',
    getParentRoute: () => WindowMainSidebarRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/window/main': typeof WindowMainSidebarRouteRouteWithChildren
  '/window/main/splash/': typeof WindowMainSplashIndexRoute
  '/window/main/home/': typeof WindowMainSidebarHomeIndexRoute
  '/window/main/settings/': typeof WindowMainSidebarSettingsIndexRoute
  '/window/main/intentions/new/': typeof WindowMainSidebarIntentionsNewIndexRoute
  '/window/main/settings/general/': typeof WindowMainSidebarSettingsGeneralIndexRoute
}
export interface FileRoutesByTo {
  '/window/main': typeof WindowMainSidebarRouteRouteWithChildren
  '/window/main/splash': typeof WindowMainSplashIndexRoute
  '/window/main/home': typeof WindowMainSidebarHomeIndexRoute
  '/window/main/settings': typeof WindowMainSidebarSettingsIndexRoute
  '/window/main/intentions/new': typeof WindowMainSidebarIntentionsNewIndexRoute
  '/window/main/settings/general': typeof WindowMainSidebarSettingsGeneralIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/window/main/_sidebar': typeof WindowMainSidebarRouteRouteWithChildren
  '/window/main/splash/': typeof WindowMainSplashIndexRoute
  '/window/main/_sidebar/home/': typeof WindowMainSidebarHomeIndexRoute
  '/window/main/_sidebar/settings/': typeof WindowMainSidebarSettingsIndexRoute
  '/window/main/_sidebar/intentions/new/': typeof WindowMainSidebarIntentionsNewIndexRoute
  '/window/main/_sidebar/settings/general/': typeof WindowMainSidebarSettingsGeneralIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/window/main'
    | '/window/main/splash/'
    | '/window/main/home/'
    | '/window/main/settings/'
    | '/window/main/intentions/new/'
    | '/window/main/settings/general/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/window/main'
    | '/window/main/splash'
    | '/window/main/home'
    | '/window/main/settings'
    | '/window/main/intentions/new'
    | '/window/main/settings/general'
  id:
    | '__root__'
    | '/window/main/_sidebar'
    | '/window/main/splash/'
    | '/window/main/_sidebar/home/'
    | '/window/main/_sidebar/settings/'
    | '/window/main/_sidebar/intentions/new/'
    | '/window/main/_sidebar/settings/general/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WindowMainSidebarRouteRoute: typeof WindowMainSidebarRouteRouteWithChildren
  WindowMainSplashIndexRoute: typeof WindowMainSplashIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/window/main/_sidebar': {
      id: '/window/main/_sidebar'
      path: '/window/main'
      fullPath: '/window/main'
      preLoaderRoute: typeof WindowMainSidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window/main/splash/': {
      id: '/window/main/splash/'
      path: '/window/main/splash'
      fullPath: '/window/main/splash/'
      preLoaderRoute: typeof WindowMainSplashIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window/main/_sidebar/settings/': {
      id: '/window/main/_sidebar/settings/'
      path: '/settings'
      fullPath: '/window/main/settings/'
      preLoaderRoute: typeof WindowMainSidebarSettingsIndexRouteImport
      parentRoute: typeof WindowMainSidebarRouteRoute
    }
    '/window/main/_sidebar/home/': {
      id: '/window/main/_sidebar/home/'
      path: '/home'
      fullPath: '/window/main/home/'
      preLoaderRoute: typeof WindowMainSidebarHomeIndexRouteImport
      parentRoute: typeof WindowMainSidebarRouteRoute
    }
    '/window/main/_sidebar/settings/general/': {
      id: '/window/main/_sidebar/settings/general/'
      path: '/settings/general'
      fullPath: '/window/main/settings/general/'
      preLoaderRoute: typeof WindowMainSidebarSettingsGeneralIndexRouteImport
      parentRoute: typeof WindowMainSidebarRouteRoute
    }
    '/window/main/_sidebar/intentions/new/': {
      id: '/window/main/_sidebar/intentions/new/'
      path: '/intentions/new'
      fullPath: '/window/main/intentions/new/'
      preLoaderRoute: typeof WindowMainSidebarIntentionsNewIndexRouteImport
      parentRoute: typeof WindowMainSidebarRouteRoute
    }
  }
}

interface WindowMainSidebarRouteRouteChildren {
  WindowMainSidebarHomeIndexRoute: typeof WindowMainSidebarHomeIndexRoute
  WindowMainSidebarSettingsIndexRoute: typeof WindowMainSidebarSettingsIndexRoute
  WindowMainSidebarIntentionsNewIndexRoute: typeof WindowMainSidebarIntentionsNewIndexRoute
  WindowMainSidebarSettingsGeneralIndexRoute: typeof WindowMainSidebarSettingsGeneralIndexRoute
}

const WindowMainSidebarRouteRouteChildren: WindowMainSidebarRouteRouteChildren =
  {
    WindowMainSidebarHomeIndexRoute: WindowMainSidebarHomeIndexRoute,
    WindowMainSidebarSettingsIndexRoute: WindowMainSidebarSettingsIndexRoute,
    WindowMainSidebarIntentionsNewIndexRoute:
      WindowMainSidebarIntentionsNewIndexRoute,
    WindowMainSidebarSettingsGeneralIndexRoute:
      WindowMainSidebarSettingsGeneralIndexRoute,
  }

const WindowMainSidebarRouteRouteWithChildren =
  WindowMainSidebarRouteRoute._addFileChildren(
    WindowMainSidebarRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  WindowMainSidebarRouteRoute: WindowMainSidebarRouteRouteWithChildren,
  WindowMainSplashIndexRoute: WindowMainSplashIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
