/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WindowMainSidebarRouteRouteImport } from './routes/window.main._sidebar/route'
import { Route as WindowMainSplashIndexRouteImport } from './routes/window.main.splash/index'
import { Route as WindowMainSidebarHomeIndexRouteImport } from './routes/window.main._sidebar.home/index'

const WindowMainSidebarRouteRoute = WindowMainSidebarRouteRouteImport.update({
  id: '/window/main/_sidebar',
  path: '/window/main',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowMainSplashIndexRoute = WindowMainSplashIndexRouteImport.update({
  id: '/window/main/splash/',
  path: '/window/main/splash/',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowMainSidebarHomeIndexRoute =
  WindowMainSidebarHomeIndexRouteImport.update({
    id: '/home/',
    path: '/home/',
    getParentRoute: () => WindowMainSidebarRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/window/main': typeof WindowMainSidebarRouteRouteWithChildren
  '/window/main/splash/': typeof WindowMainSplashIndexRoute
  '/window/main/home/': typeof WindowMainSidebarHomeIndexRoute
}
export interface FileRoutesByTo {
  '/window/main': typeof WindowMainSidebarRouteRouteWithChildren
  '/window/main/splash': typeof WindowMainSplashIndexRoute
  '/window/main/home': typeof WindowMainSidebarHomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/window/main/_sidebar': typeof WindowMainSidebarRouteRouteWithChildren
  '/window/main/splash/': typeof WindowMainSplashIndexRoute
  '/window/main/_sidebar/home/': typeof WindowMainSidebarHomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/window/main' | '/window/main/splash/' | '/window/main/home/'
  fileRoutesByTo: FileRoutesByTo
  to: '/window/main' | '/window/main/splash' | '/window/main/home'
  id:
    | '__root__'
    | '/window/main/_sidebar'
    | '/window/main/splash/'
    | '/window/main/_sidebar/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WindowMainSidebarRouteRoute: typeof WindowMainSidebarRouteRouteWithChildren
  WindowMainSplashIndexRoute: typeof WindowMainSplashIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/window/main/_sidebar': {
      id: '/window/main/_sidebar'
      path: '/window/main'
      fullPath: '/window/main'
      preLoaderRoute: typeof WindowMainSidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window/main/splash/': {
      id: '/window/main/splash/'
      path: '/window/main/splash'
      fullPath: '/window/main/splash/'
      preLoaderRoute: typeof WindowMainSplashIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window/main/_sidebar/home/': {
      id: '/window/main/_sidebar/home/'
      path: '/home'
      fullPath: '/window/main/home/'
      preLoaderRoute: typeof WindowMainSidebarHomeIndexRouteImport
      parentRoute: typeof WindowMainSidebarRouteRoute
    }
  }
}

interface WindowMainSidebarRouteRouteChildren {
  WindowMainSidebarHomeIndexRoute: typeof WindowMainSidebarHomeIndexRoute
}

const WindowMainSidebarRouteRouteChildren: WindowMainSidebarRouteRouteChildren =
  {
    WindowMainSidebarHomeIndexRoute: WindowMainSidebarHomeIndexRoute,
  }

const WindowMainSidebarRouteRouteWithChildren =
  WindowMainSidebarRouteRoute._addFileChildren(
    WindowMainSidebarRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  WindowMainSidebarRouteRoute: WindowMainSidebarRouteRouteWithChildren,
  WindowMainSplashIndexRoute: WindowMainSplashIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
