
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getAppInfo() : Promise<AppInfoDto> {
    return await TAURI_INVOKE("get_app_info");
},
async getSystemTypography() : Promise<SystemTypographyDto> {
    return await TAURI_INVOKE("get_system_typography");
},
async openDataDirectory() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_data_directory") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<AppSettings> {
    return await TAURI_INVOKE("get_settings");
},
async setSettings(settings: AppSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getIntentions() : Promise<Result<Intention[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_intentions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getIntention(intentionId: number) : Promise<Result<Intention | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_intention", { intentionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getActiveIntentionSessions() : Promise<Result<IntentionSession[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_active_intention_sessions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getActiveIntentionSession(intentionId: number) : Promise<Result<IntentionSession | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_active_intention_session", { intentionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createIntention(params: CreateIntentionParams) : Promise<Result<Intention, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_intention", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateIntention(params: UpdateIntentionParams) : Promise<Result<Intention, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_intention", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteIntention(intentionId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_intention", { intentionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startIntention(intentionId: number) : Promise<Result<IntentionSession, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_intention", { intentionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async completeIntention(intentionId: number, endConditionId: number | null) : Promise<Result<IntentionSession, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("complete_intention", { intentionId, endConditionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopIntention(intentionId: number) : Promise<Result<IntentionSession, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_intention", { intentionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getShortcutConfigs() : Promise<ShortcutActionConfigDto[]> {
    return await TAURI_INVOKE("get_shortcut_configs");
},
/**
 * Searches cached catalog items by query.
 */
async searchCatalog(params: SearchCatalogParams) : Promise<Result<CatalogSearchResultDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_catalog", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
appSettingsChangedEvent: AppSettingsChangedEvent,
catalogAssetLoadedEvent: CatalogAssetLoadedEvent,
intentionCreatedEvent: IntentionCreatedEvent,
intentionDeletedEvent: IntentionDeletedEvent,
intentionSessionCompletedEvent: IntentionSessionCompletedEvent,
intentionSessionStartedEvent: IntentionSessionStartedEvent,
intentionSessionStoppedEvent: IntentionSessionStoppedEvent,
intentionUpdatedEvent: IntentionUpdatedEvent,
shortcutTriggeredEvent: ShortcutTriggeredEvent
}>({
appSettingsChangedEvent: "app-settings-changed-event",
catalogAssetLoadedEvent: "catalog-asset-loaded-event",
intentionCreatedEvent: "intention-created-event",
intentionDeletedEvent: "intention-deleted-event",
intentionSessionCompletedEvent: "intention-session-completed-event",
intentionSessionStartedEvent: "intention-session-started-event",
intentionSessionStoppedEvent: "intention-session-stopped-event",
intentionUpdatedEvent: "intention-updated-event",
shortcutTriggeredEvent: "shortcut-triggered-event"
})

/** user-defined constants **/



/** user-defined types **/

export type App = { 
/**
 * Database row identifier for persisted app records.
 */
id: number; 
/**
 * Stable app identifier used as the canonical app key across platforms.
 */
stableId: string; name: string | null; 
/**
 * macOS bundle identifier when the app provides one.
 */
bundleId: string | null; 
/**
 * Executable or bundle path used to derive stable IDs for unbundled apps.
 */
processPath: string | null; icon: string | null; color: string | null }
export type AppDistribution = "appStore" | "direct"
export type AppInfoDto = { version: string; stage: Stage; distribution: AppDistribution }
export type AppSettings = { version: SettingsVersion; appearance: AppearanceSettings; developer: DeveloperSettings; 
/**
 * User overrides per action. Absent key = use default. None value = shortcut cleared.
 */
shortcuts: Partial<{ [key in ShortcutAction]: KeyboardShortcut | null }> }
export type AppSettingsChangedEvent = AppSettings
export type AppearanceSettings = { theme: Theme; fontScale: number }
export type CatalogAppSearchResultDto = { stableId: string; name: string | null; bundleId: string | null; processPath: string | null; icon: string | null; color: string | null }
export type CatalogAssetLoadedEvent = { itemId: CatalogItemId; icon: string | null; color: string | null }
export type CatalogIconMode = { type: "skip" } | { type: "eager"; includeColor: boolean } | { type: "lazy"; includeColor: boolean }
export type CatalogItemId = { type: "app"; stableId: string; bundleId: string | null } | { type: "website"; hostname: string }
export type CatalogSearchResultDto = { type: "app"; app: CatalogAppSearchResultDto; score: number } | { type: "website"; website: CatalogWebsiteSearchResultDto; score: number }
export type CatalogWebsiteSearchResultDto = { hostname: string; name: string | null; icon: string | null; color: string | null }
export type CreateIntentionParams = { name: string; behavior: WriteIntentionBehaviorParams; conditions: WriteIntentionConditionParams[] }
export type DateOnly = number
export type DeveloperSettings = { enabled: boolean }
export type Intention = { id: number; name: string; behavior: IntentionBehavior; conditions: IntentionCondition[]; updatedAt: number; createdAt: number }
export type IntentionBehavior = ({ type: "block" } & IntentionBlock) | { type: "break" }
export type IntentionBlock = { enforcementMode: IntentionEnforcementMode; scope: IntentionBlockScope; apps: App[]; websites: Website[] }
export type IntentionBlockScope = "blockTargets" | "allowTargets" | "wholeDevice"
export type IntentionCondition = { id: number; transition: IntentionConditionTransition; rule: IntentionConditionRule; updatedAt: number; createdAt: number }
export type IntentionConditionAfterTransitionRule = { anchorTransition: IntentionConditionTransition; offsetMs: number }
export type IntentionConditionDateTimeRule = { dateEpochDays: DateOnly; timeOfDayMs: TimeOnly; triggerAt: number }
export type IntentionConditionRule = ({ type: "schedule" } & IntentionConditionScheduleRule) | ({ type: "dateTime" } & IntentionConditionDateTimeRule) | ({ type: "afterTransition" } & IntentionConditionAfterTransitionRule) | { type: "manual" }
export type IntentionConditionScheduleRule = { timeOfDayMs: TimeOnly; weekdaysMask: WeekdayMask | null }
export type IntentionConditionTransition = "start" | "end"
export type IntentionCreatedEvent = { intentionId: number }
export type IntentionDeletedEvent = { intentionId: number }
export type IntentionEnforcementMode = "casual" | "balanced" | "strict"
export type IntentionSession = { id: number; intentionId: number; status: IntentionSessionStatus; startedAt: number; startConditionId: number | null; endedAt: number | null; endConditionId: number | null; updatedAt: number; createdAt: number }
export type IntentionSessionCompletedEvent = { intentionId: number; sessionId: number }
export type IntentionSessionStartedEvent = { intentionId: number; sessionId: number }
export type IntentionSessionStatus = "active" | "completed" | "stopped"
export type IntentionSessionStoppedEvent = { intentionId: number; sessionId: number }
export type IntentionUpdatedEvent = { intentionId: number }
export type KeyboardShortcut = { modifiers: ShortcutModifier[]; 
/**
 * A browser KeyboardEvent.code value, e.g. "KeyK", "KeyB".
 */
code: string }
export type SearchCatalogParams = { query: string; limit: number | null; includeIcon: CatalogIconMode | null }
export type SettingsVersion = "0.0.1"
export type ShortcutAction = "search" | "newIntention" | "toggleSidebar"
export type ShortcutActionConfigDto = { action: ShortcutAction; isGlobal: boolean; shortcut: KeyboardShortcut | null }
export type ShortcutModifier = "meta" | "ctrl" | "alt" | "shift"
export type ShortcutTriggeredEvent = ShortcutAction
export type Stage = "dev" | "prod"
export type SystemTypographyDto = { baseFontSize: number; smallFontSize: number }
export type Theme = "light" | "dark" | "auto"
export type TimeOnly = number
export type UpdateIntentionParams = { intentionId: number; name: string; behavior: WriteIntentionBehaviorParams; conditions: WriteIntentionConditionParams[] }
export type Website = { 
/**
 * Database row identifier for persisted website records.
 */
id: number; 
/**
 * Canonical website hostname used as the stable website key.
 */
hostname: string; name: string | null; icon: string | null; color: string | null }
export type WeekdayMask = number
export type WriteIntentionBehaviorParams = ({ type: "block" } & WriteIntentionBlockParams) | { type: "break" }
export type WriteIntentionBlockAppTargetParams = { stableId: string; name: string | null; bundleId: string | null; processPath: string | null; icon: string | null; color: string | null }
export type WriteIntentionBlockParams = { enforcementMode: IntentionEnforcementMode; scope: IntentionBlockScope; targets: WriteIntentionBlockTargetParams[] }
export type WriteIntentionBlockTargetParams = ({ type: "app" } & WriteIntentionBlockAppTargetParams) | ({ type: "website" } & WriteIntentionBlockWebsiteTargetParams)
export type WriteIntentionBlockWebsiteTargetParams = { hostname: string; name: string | null; icon: string | null; color: string | null }
export type WriteIntentionConditionDateTimeRuleParams = { dateEpochDays: DateOnly; timeOfDayMs: TimeOnly }
export type WriteIntentionConditionParams = { transition: IntentionConditionTransition; rule: WriteIntentionConditionRuleParams }
export type WriteIntentionConditionRuleParams = ({ type: "schedule" } & IntentionConditionScheduleRule) | ({ type: "dateTime" } & WriteIntentionConditionDateTimeRuleParams) | ({ type: "afterTransition" } & IntentionConditionAfterTransitionRule) | { type: "manual" }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
