
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getAppInfo() : Promise<AppInfoDto> {
    return await TAURI_INVOKE("get_app_info");
},
async openDataDirectory() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_data_directory") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<AppSettings> {
    return await TAURI_INVOKE("get_settings");
},
async setSettings(settings: AppSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getIntention(intentionId: number) : Promise<Result<Intention | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_intention", { intentionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createIntention(params: CreateIntentionParams) : Promise<Result<Intention, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_intention", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getShortcutConfigs() : Promise<ShortcutActionConfigDto[]> {
    return await TAURI_INVOKE("get_shortcut_configs");
}
}

/** user-defined events **/


export const events = __makeEvents__<{
appSettingsChangedEvent: AppSettingsChangedEvent,
intentionCreatedEvent: IntentionCreatedEvent,
intentionUpdatedEvent: IntentionUpdatedEvent,
shortcutTriggeredEvent: ShortcutTriggeredEvent
}>({
appSettingsChangedEvent: "app-settings-changed-event",
intentionCreatedEvent: "intention-created-event",
intentionUpdatedEvent: "intention-updated-event",
shortcutTriggeredEvent: "shortcut-triggered-event"
})

/** user-defined constants **/



/** user-defined types **/

export type AppDistribution = "appStore" | "direct"
export type AppInfoDto = { version: string; stage: Stage; distribution: AppDistribution }
export type AppSettings = { version: SettingsVersion; appearance: AppearanceSettings; developer: DeveloperSettings; 
/**
 * User overrides per action. Absent key = use default. None value = shortcut cleared.
 */
shortcuts: Partial<{ [key in ShortcutAction]: KeyboardShortcut | null }> }
export type AppSettingsChangedEvent = AppSettings
export type AppearanceSettings = { theme: Theme }
export type CreateIntentionBehaviorParams = { type: "block" } | { type: "break" }
export type CreateIntentionParams = { name: string; behavior: CreateIntentionBehaviorParams }
export type DeveloperSettings = { enabled: boolean }
export type Intention = { id: number; name: string; behavior: IntentionBehavior; conditions: IntentionCondition[]; createdAt: number }
export type IntentionBehavior = ({ type: "block" } & IntentionBlock) | { type: "break" }
export type IntentionBlock = { enforcementMode: IntentionEnforcementMode; targetScope: IntentionBlockTargetScope; appIds: number[]; websiteIds: number[]; createdAt: number }
export type IntentionBlockTargetScope = "selectedTargets" | "wholeDevice"
export type IntentionCondition = { id: number; phase: IntentionConditionPhase; rule: IntentionConditionRule; createdAt: number }
export type IntentionConditionPhase = "start" | "end"
export type IntentionConditionRule = { type: "time"; timeOfDay: string; weekdays: number[] | null } | { type: "manual" }
export type IntentionCreatedEvent = { intentionId: number }
export type IntentionEnforcementMode = "casual" | "balanced" | "hardcore"
export type IntentionUpdatedEvent = { intentionId: number }
export type KeyboardShortcut = { modifiers: ShortcutModifier[]; 
/**
 * A browser KeyboardEvent.code value, e.g. "KeyK", "KeyB".
 */
code: string }
export type SettingsVersion = "0.0.1"
export type ShortcutAction = "search" | "toggleSidebar"
export type ShortcutActionConfigDto = { action: ShortcutAction; isGlobal: boolean; shortcut: KeyboardShortcut | null }
export type ShortcutModifier = "meta" | "ctrl" | "alt" | "shift"
export type ShortcutTriggeredEvent = ShortcutAction
export type Stage = "dev" | "prod"
export type Theme = "light" | "dark" | "auto"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
