name: Develop

on:
  push:
    branches: [develop]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  desktop_ci:
    name: Desktop CI
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run CI
        uses: ./.github/actions/ci
        with:
          app-directory: apps/desktop
          build-script: ui:build

  web_ci:
    name: Web CI
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run CI
        uses: ./.github/actions/ci
        with:
          app-directory: apps/web
